import React, { useState, useEffect, useMemo } from 'react';
import { DataService, subscribeToRealtime } from '../../services/dataService';
import { 
  FileText, Upload, Plus, DollarSign, Calendar, RefreshCw, 
  Trash2, ClipboardList, CheckCircle, Search, Filter, ShieldAlert,
  Download, ArrowUpRight, ArrowDownRight
} from 'lucide-react';

const formatNoRound = (num) => {
  if (num === undefined || num === null || isNaN(num)) return '0.00';
  const factor = 100;
  const truncated = Math.trunc(num * factor) / factor;
  const parts = truncated.toString().split('.');
  if (parts.length === 1) return parts[0] + '.00';
  if (parts[1].length === 1) return parts[0] + '.' + parts[1] + '0';
  return parts[0] + '.' + parts[1].substring(0, 2);
};

export default function TaxDeclaration() {
  const [sales, setSales] = useState([]);
  const [manualInvoices, setManualInvoices] = useState([]);
  const [activeSubTab, setActiveSubTab] = useState('summary'); // 'summary' | 'sales' | 'purchases'
  
  // Search & Filter
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth()); // 0-11
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());
  const [searchQuery, setSearchQuery] = useState('');

  // Manual entry modal/form states
  const [showAddModal, setShowAddModal] = useState(false);
  const [entryType, setEntryType] = useState('purchase'); // 'purchase' (Compra) | 'sale' (Venta Manual)
  const [docType, setDocType] = useState('Factura'); // 'Factura' | 'Boleta'
  const [docNumber, setDocNumber] = useState('');
  const [clientName, setClientName] = useState('');
  const [clientRuc, setClientRuc] = useState('');
  const [amountTotal, setAmountTotal] = useState('');
  const [dateStr, setDateStr] = useState(new Date().toISOString().slice(0, 10));

  // PDF import helper mock
  const [importingPdf, setImportingPdf] = useState(false);
  const [pdfSuccessMessage, setPdfSuccessMessage] = useState('');

  const loadData = async () => {
    // Get sales automatically generated by system
    const dbSales = await DataService.getSales();
    // Filter active sales that have invoice numbers
    const cleanSales = dbSales.filter(s => s.status !== 'voided' && s.document_type !== 'Sin Datos');
    setSales(cleanSales);

    // Get manually entered invoices (stored in localStorage to persist)
    const stored = localStorage.getItem('arven_manual_tax_declarations');
    if (stored) {
      try {
        setManualInvoices(JSON.parse(stored));
      } catch (e) {
        console.error(e);
      }
    }
  };

  useEffect(() => {
    loadData();
    const unsubscribe = subscribeToRealtime(() => {
      loadData();
    });
    return () => unsubscribe();
  }, []);

  const saveManualInvoices = (updated) => {
    setManualInvoices(updated);
    localStorage.setItem('arven_manual_tax_declarations', JSON.stringify(updated));
  };

  // PDF manual import simulator
  const handlePdfUpload = (e) => {
    const file = e.target.files[0];
    if (!file) return;

    setImportingPdf(true);
    setPdfSuccessMessage('');
    
    // Simulate OCR pdf scanner extract
    setTimeout(() => {
      // Mock extract parameters based on file name or random variables
      const isFactura = file.name.toLowerCase().includes('factura') || Math.random() > 0.5;
      const parsedTotal = (Math.random() * 500 + 120).toFixed(2);
      const parsedNum = `E001-${Math.floor(Math.random() * 8000) + 1000}`;
      
      setEntryType('purchase'); // defaults to buying since they import invoice PDFs
      setDocType(isFactura ? 'Factura' : 'Boleta');
      setDocNumber(parsedNum);
      setClientName(isFactura ? 'DISTRIBUIDORA TEXTIL S.A.C.' : 'Proveedor Local');
      setClientRuc(isFactura ? '20608765432' : '10457689091');
      setAmountTotal(parsedTotal);
      
      setImportingPdf(false);
      setPdfSuccessMessage(`✓ Escaneado con éxito: ${file.name} (RUC: ${isFactura ? '20608765432' : '10457689091'} - Total: S/. ${parsedTotal})`);
    }, 1800);
  };

  const handleSaveManualEntry = (e) => {
    e.preventDefault();
    if (!docNumber.trim() || !clientName.trim() || !amountTotal.trim()) {
      alert('Por favor completa los campos principales (Número, Nombre y Monto).');
      return;
    }

    const newEntry = {
      id: 'tax-' + Date.now(),
      entryType, // 'purchase' | 'sale'
      documentType: docType,
      invoiceNumber: docNumber.trim(),
      customerName: clientName.trim(),
      customerDocument: clientRuc.trim(),
      totalAmount: parseFloat(amountTotal) || 0,
      createdAt: new Date(dateStr + 'T12:00:00').toISOString(),
      isManual: true
    };

    const updated = [newEntry, ...manualInvoices];
    saveManualInvoices(updated);
    
    // reset form
    setDocNumber('');
    setClientName('');
    setClientRuc('');
    setAmountTotal('');
    setPdfSuccessMessage('');
    setShowAddModal(false);
    alert('Comprobante registrado con éxito.');
  };

  const handleDeleteManual = (id) => {
    if (window.confirm('¿Deseas eliminar este comprobante de la declaración?')) {
      const updated = manualInvoices.filter(item => item.id !== id);
      saveManualInvoices(updated);
    }
  };

  // Computations & Filter
  const filteredSales = useMemo(() => {
    return sales.filter(s => {
      const d = new Date(s.created_at);
      const matchesDate = d.getMonth() === selectedMonth && d.getFullYear() === selectedYear;
      const matchesSearch = s.invoice_number.toLowerCase().includes(searchQuery.toLowerCase()) || 
                            s.customer_name.toLowerCase().includes(searchQuery.toLowerCase());
      return matchesDate && matchesSearch;
    });
  }, [sales, selectedMonth, selectedYear, searchQuery]);

  const filteredPurchases = useMemo(() => {
    return manualInvoices.filter(p => {
      const d = new Date(p.createdAt);
      const matchesDate = d.getMonth() === selectedMonth && d.getFullYear() === selectedYear;
      const matchesSearch = p.invoiceNumber.toLowerCase().includes(searchQuery.toLowerCase()) || 
                            p.customerName.toLowerCase().includes(searchQuery.toLowerCase());
      const isPurchase = p.entryType === 'purchase';
      return matchesDate && matchesSearch && isPurchase;
    });
  }, [manualInvoices, selectedMonth, selectedYear, searchQuery]);

  // Merge manual sales if any
  const totalSalesList = useMemo(() => {
    const manualSales = manualInvoices.filter(p => {
      const d = new Date(p.createdAt);
      const matchesDate = d.getMonth() === selectedMonth && d.getFullYear() === selectedYear;
      const matchesSearch = p.invoiceNumber.toLowerCase().includes(searchQuery.toLowerCase()) || 
                            p.customerName.toLowerCase().includes(searchQuery.toLowerCase());
      return matchesDate && matchesSearch && p.entryType === 'sale';
    });

    // Map DB sales to consistent layout
    const dbMapped = filteredSales.map(s => ({
      id: s.id,
      documentType: s.document_type || 'Boleta',
      invoiceNumber: s.invoice_number,
      customerName: s.customer_name,
      customerDocument: s.customer_document || '—',
      totalAmount: s.total_amount,
      createdAt: s.created_at,
      isManual: false
    }));

    return [...dbMapped, ...manualSales].sort((a,b) => new Date(b.createdAt) - new Date(a.createdAt));
  }, [filteredSales, manualInvoices, selectedMonth, selectedYear, searchQuery]);

  // Tax calculations
  const summary = useMemo(() => {
    let salesTotal = 0;
    let purchasesTotal = 0;

    totalSalesList.forEach(s => { salesTotal += s.totalAmount; });
    filteredPurchases.forEach(p => { purchasesTotal += p.totalAmount; });

    // SUNAT taxes: 18% IGV
    const salesBase = salesTotal / 1.18;
    const salesIgv = salesTotal - salesBase;

    const purchasesBase = purchasesTotal / 1.18;
    const purchasesIgv = purchasesTotal - purchasesBase;

    // IGV to pay
    const igvResult = salesIgv - purchasesIgv;

    return {
      salesTotal,
      salesBase,
      salesIgv,
      purchasesTotal,
      purchasesBase,
      purchasesIgv,
      igvResult
    };
  }, [totalSalesList, filteredPurchases]);

  // Export Table to XML-styled real Excel
  const handleExportExcel = () => {
    let xls = `
      <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
      <head><meta charset="utf-8"/><style>
        table { border-collapse: collapse; }
        th { background-color: #111111; color: #ffffff; font-weight: bold; }
        td, th { border: 1px solid #dddddd; padding: 8px; text-align: left; }
        .accent { color: #C5A880; font-weight: bold; }
      </style></head>
      <body>
      <h2>Reporte Mensual Declaración SUNAT</h2>
      <p>Mes: ${selectedMonth + 1} | Año: ${selectedYear}</p>
      
      <h3>RESUMEN TRIBUTARIO</h3>
      <table>
        <tr><th>Concepto</th><th>Base Gravada</th><th>IGV (18%)</th><th>Total</th></tr>
        <tr><td>Ventas declaradas</td><td>S/. ${formatNoRound(summary.salesBase)}</td><td>S/. ${formatNoRound(summary.salesIgv)}</td><td>S/. ${formatNoRound(summary.salesTotal)}</td></tr>
        <tr><td>Compras declaradas</td><td>S/. ${formatNoRound(summary.purchasesBase)}</td><td>S/. ${formatNoRound(summary.purchasesIgv)}</td><td>S/. ${formatNoRound(summary.purchasesTotal)}</td></tr>
        <tr class="accent"><td>IGV RESULTANTE A PAGAR</td><td>—</td><td>—</td><td>S/. ${formatNoRound(summary.igvResult)}</td></tr>
      </table>
      
      <h3>DETALLE DE COMPROBANTES DE VENTAS</h3>
      <table>
        <tr><th>Fecha</th><th>Tipo</th><th>Número</th><th>Adquiriente</th><th>Doc. Identidad</th><th>Monto Total</th></tr>
        ${totalSalesList.map(s => `
          <tr>
            <td>${new Date(s.createdAt).toLocaleDateString()}</td>
            <td>${s.documentType}</td>
            <td>${s.invoiceNumber}</td>
            <td>${s.customerName}</td>
            <td>${s.customerDocument}</td>
            <td>S/. ${formatNoRound(s.totalAmount)}</td>
          </tr>
        `).join('')}
      </table>
      
      <h3>DETALLE DE COMPROBANTES DE COMPRAS</h3>
      <table>
        <tr><th>Fecha</th><th>Tipo</th><th>Número</th><th>Proveedor</th><th>RUC Proveedor</th><th>Monto Total</th></tr>
        ${filteredPurchases.map(p => `
          <tr>
            <td>${new Date(p.createdAt).toLocaleDateString()}</td>
            <td>${p.documentType}</td>
            <td>${p.invoiceNumber}</td>
            <td>${p.customerName}</td>
            <td>${p.customerDocument}</td>
            <td>S/. ${formatNoRound(p.totalAmount)}</td>
          </tr>
        `).join('')}
      </table>
      </body>
      </html>
    `;

    const blob = new Blob([xls], { type: 'application/vnd.ms-excel' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `Declaracion_SUNAT_${selectedMonth + 1}_${selectedYear}.xls`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      
      {/* HEADER */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '16px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <div style={{
            width: '42px', height: '42px', borderRadius: '10px',
            background: 'linear-gradient(135deg, #111 0%, #1a1a2e 100%)',
            display: 'flex', alignItems: 'center', justifyContent: 'center'
          }}>
            <FileText size={20} color="#C5A880" />
          </div>
          <div>
            <h2 style={{ fontSize: '20px', fontWeight: 800, color: '#111', margin: 0 }}>Declaración y Seguimiento SUNAT</h2>
            <p style={{ fontSize: '12px', color: '#6B7280', margin: '2px 0 0' }}>Declaraciones mensuales de IGV, registro automatizado de ventas e importación de compras</p>
          </div>
        </div>

        {/* TOP CONTROLS */}
        <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
          <select value={selectedMonth} onChange={e => setSelectedMonth(parseInt(e.target.value))} style={{ padding: '8px 12px', border: '1px solid #E5E7EB', borderRadius: '6px', fontSize: '13px', fontWeight: 600, backgroundColor: '#FFF' }}>
            {['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'].map((m, i) => (
              <option key={i} value={i}>{m}</option>
            ))}
          </select>
          <select value={selectedYear} onChange={e => setSelectedYear(parseInt(e.target.value))} style={{ padding: '8px 12px', border: '1px solid #E5E7EB', borderRadius: '6px', fontSize: '13px', fontWeight: 600, backgroundColor: '#FFF' }}>
            {[2024, 2025, 2026, 2027].map(y => (
              <option key={y} value={y}>{y}</option>
            ))}
          </select>

          <button onClick={handleExportExcel} style={{ padding: '8px 14px', fontSize: '13px', fontWeight: 700, border: '1px solid #10B981', color: '#10B981', backgroundColor: '#FFF', borderRadius: '6px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px' }}>
            <Download size={14} /> Exportar Excel
          </button>
          
          <button onClick={() => setShowAddModal(true)} style={{ padding: '8px 16px', fontSize: '13px', fontWeight: 700, border: 'none', backgroundColor: '#111', color: '#C5A880', borderRadius: '6px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px' }}>
            <Plus size={14} /> Registrar Comprobante
          </button>
        </div>
      </div>

      {/* KPI DASHBOARD CARDS */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '20px' }}>
        
        {/* Sales Card */}
        <div style={{ backgroundColor: '#FFF', border: '1px solid #E5E7EB', borderRadius: '12px', padding: '20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <span style={{ fontSize: '10px', fontWeight: 700, color: '#9CA3AF', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Ventas del Periodo</span>
            <h3 style={{ fontSize: '22px', fontWeight: 800, color: '#111', margin: '4px 0' }}>S/. {formatNoRound(summary.salesTotal)}</h3>
            <span style={{ fontSize: '10px', color: '#10B981', display: 'flex', alignItems: 'center', gap: '2px' }}>
              <ArrowUpRight size={10} /> IGV: S/. {formatNoRound(summary.salesIgv)}
            </span>
          </div>
          <div style={{ width: '42px', height: '42px', borderRadius: '10px', backgroundColor: '#D1FAE5', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <ArrowUpRight size={20} color="#10B981" />
          </div>
        </div>

        {/* Purchases Card */}
        <div style={{ backgroundColor: '#FFF', border: '1px solid #E5E7EB', borderRadius: '12px', padding: '20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <span style={{ fontSize: '10px', fontWeight: 700, color: '#9CA3AF', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Compras Facturadas</span>
            <h3 style={{ fontSize: '22px', fontWeight: 800, color: '#111', margin: '4px 0' }}>S/. {formatNoRound(summary.purchasesTotal)}</h3>
            <span style={{ fontSize: '10px', color: '#EF4444', display: 'flex', alignItems: 'center', gap: '2px' }}>
              <ArrowDownRight size={10} /> IGV: S/. {formatNoRound(summary.purchasesIgv)}
            </span>
          </div>
          <div style={{ width: '42px', height: '42px', borderRadius: '10px', backgroundColor: '#FEE2E2', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <ArrowDownRight size={20} color="#EF4444" />
          </div>
        </div>

        {/* IGV Resulting Card */}
        <div style={{
          background: 'linear-gradient(135deg, #111 0%, #1a1a2e 100%)',
          borderRadius: '12px', padding: '20px', color: '#FFF', display: 'flex', justifyContent: 'space-between', alignItems: 'center'
        }}>
          <div>
            <span style={{ fontSize: '10px', fontWeight: 700, color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>IGV Resultante (SUNAT)</span>
            <h3 style={{ fontSize: '22px', fontWeight: 800, color: '#C5A880', margin: '4px 0' }}>S/. {formatNoRound(summary.igvResult)}</h3>
            <span style={{ fontSize: '10px', color: 'rgba(255,255,255,0.6)' }}>
              {summary.igvResult >= 0 ? 'Monto a pagar' : 'Saldo a favor'}
            </span>
          </div>
          <div style={{ width: '42px', height: '42px', borderRadius: '10px', backgroundColor: 'rgba(197,168,128,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <DollarSign size={20} color="#C5A880" />
          </div>
        </div>
      </div>

      {/* FILTER AND SEARCH BAR */}
      <div style={{ backgroundColor: '#FFF', border: '1px solid #E5E7EB', borderRadius: '12px', padding: '14px 20px', display: 'flex', gap: '14px', alignItems: 'center' }}>
        <Search size={16} color="#9CA3AF" />
        <input 
          type="text" 
          value={searchQuery} 
          onChange={e => setSearchQuery(e.target.value)} 
          placeholder="Buscar por N° comprobante o nombre..." 
          style={{ flex: 1, border: 'none', outline: 'none', fontSize: '13px' }} 
        />
        
        <div style={{ display: 'flex', border: '1px solid #E5E7EB', borderRadius: '6px', overflow: 'hidden' }}>
          {[
            { id: 'summary', label: 'Resumen' },
            { id: 'sales', label: `Ventas (${totalSalesList.length})` },
            { id: 'purchases', label: `Compras (${filteredPurchases.length})` }
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveSubTab(tab.id)}
              style={{
                padding: '6px 14px', border: 'none', cursor: 'pointer', fontSize: '12px', fontWeight: 700,
                backgroundColor: activeSubTab === tab.id ? '#111' : '#FFF',
                color: activeSubTab === tab.id ? '#C5A880' : '#4B5563'
              }}
            >
              {tab.label}
            </button>
          ))}
        </div>
      </div>

      {/* ================= TAB 1: GENERAL SUMMARY ================= */}
      {activeSubTab === 'summary' && (
        <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 0.8fr', gap: '20px', alignItems: 'start' }}>
          
          <div style={{ backgroundColor: '#FFF', border: '1px solid #E5E7EB', borderRadius: '12px', padding: '20px' }}>
            <h3 style={{ fontSize: '14px', fontWeight: 800, color: '#111', marginBottom: '14px', textTransform: 'uppercase' }}>Historial del Periodo</h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              
              {totalSalesList.slice(0, 4).map(s => (
                <div key={s.id} style={{ display: 'flex', justifyContent: 'space-between', padding: '10px', borderBottom: '1px solid #F3F4F6' }}>
                  <div>
                    <span style={{ fontSize: '12px', fontWeight: 700, color: '#10B981', display: 'flex', alignItems: 'center', gap: '4px' }}>
                      🟢 VENTA ({s.documentType})
                    </span>
                    <span style={{ fontSize: '13px', fontWeight: 800, color: '#111', display: 'block', marginTop: '2px' }}>{s.invoiceNumber} — {s.customerName}</span>
                  </div>
                  <span style={{ fontSize: '14px', fontWeight: 800, color: '#111' }}>S/. {formatNoRound(s.totalAmount)}</span>
                </div>
              ))}

              {filteredPurchases.slice(0, 4).map(p => (
                <div key={p.id} style={{ display: 'flex', justifyContent: 'space-between', padding: '10px', borderBottom: '1px solid #F3F4F6' }}>
                  <div>
                    <span style={{ fontSize: '12px', fontWeight: 700, color: '#EF4444', display: 'flex', alignItems: 'center', gap: '4px' }}>
                      🔴 COMPRA ({p.documentType})
                    </span>
                    <span style={{ fontSize: '13px', fontWeight: 800, color: '#111', display: 'block', marginTop: '2px' }}>{p.invoiceNumber} — {p.customerName}</span>
                  </div>
                  <span style={{ fontSize: '14px', fontWeight: 800, color: '#111' }}>S/. {formatNoRound(p.totalAmount)}</span>
                </div>
              ))}

              {totalSalesList.length === 0 && filteredPurchases.length === 0 && (
                <div style={{ padding: '30px', textAlign: 'center', color: '#9CA3AF' }}>No hay transacciones registradas para este periodo.</div>
              )}
            </div>
          </div>

          {/* Tax summary breakdown card */}
          <div style={{ backgroundColor: '#FFF', border: '1px solid #E5E7EB', borderRadius: '12px', padding: '20px' }}>
            <h3 style={{ fontSize: '14px', fontWeight: 800, color: '#111', marginBottom: '14px', textTransform: 'uppercase' }}>Cálculo de Impuestos</h3>
            
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', fontSize: '13px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px dashed #E5E7EB', paddingBottom: '6px' }}>
                <span style={{ color: '#4B5563' }}>Ventas Brutas:</span>
                <span style={{ fontWeight: 700 }}>S/. {formatNoRound(summary.salesTotal)}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px dashed #E5E7EB', paddingBottom: '6px' }}>
                <span style={{ color: '#4B5563' }}>Base Ventas:</span>
                <span style={{ fontWeight: 700 }}>S/. {formatNoRound(summary.salesBase)}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid #E5E7EB', paddingBottom: '8px', color: '#10B981', fontWeight: 700 }}>
                <span>IGV Ventas (+):</span>
                <span>S/. {formatNoRound(summary.salesIgv)}</span>
              </div>

              <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px dashed #E5E7EB', paddingBottom: '6px', marginTop: '6px' }}>
                <span style={{ color: '#4B5563' }}>Compras Brutas:</span>
                <span style={{ fontWeight: 700 }}>S/. {formatNoRound(summary.purchasesTotal)}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px dashed #E5E7EB', paddingBottom: '6px' }}>
                <span style={{ color: '#4B5563' }}>Base Compras:</span>
                <span style={{ fontWeight: 700 }}>S/. {formatNoRound(summary.purchasesBase)}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid #E5E7EB', paddingBottom: '8px', color: '#EF4444', fontWeight: 700 }}>
                <span>IGV Compras (-):</span>
                <span>S/. {formatNoRound(summary.purchasesIgv)}</span>
              </div>

              <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '10px', padding: '10px', borderRadius: '6px', backgroundColor: '#F9FAFB', fontWeight: 800, fontSize: '14px' }}>
                <span>IGV a Liquidar:</span>
                <span style={{ color: summary.igvResult >= 0 ? '#111' : '#10B981' }}>
                  S/. {formatNoRound(summary.igvResult)}
                </span>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ================= TAB 2: DETAILED SALES LIST ================= */}
      {activeSubTab === 'sales' && (
        <div style={{ backgroundColor: '#FFF', border: '1px solid #E5E7EB', borderRadius: '12px', overflow: 'hidden' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px', textAlign: 'left' }}>
            <thead>
              <tr style={{ backgroundColor: '#F9FAFB', borderBottom: '1px solid #E5E7EB' }}>
                <th style={{ padding: '12px 18px', fontWeight: 700 }}>Fecha</th>
                <th style={{ padding: '12px 18px', fontWeight: 700 }}>Tipo</th>
                <th style={{ padding: '12px 18px', fontWeight: 700 }}>Número</th>
                <th style={{ padding: '12px 18px', fontWeight: 700 }}>Adquiriente</th>
                <th style={{ padding: '12px 18px', fontWeight: 700 }}>Doc. Identidad</th>
                <th style={{ padding: '12px 18px', fontWeight: 700, textAlign: 'right' }}>Monto Total</th>
              </tr>
            </thead>
            <tbody>
              {totalSalesList.map(s => (
                <tr key={s.id} style={{ borderBottom: '1px solid #F3F4F6' }}>
                  <td style={{ padding: '12px 18px' }}>{new Date(s.createdAt).toLocaleDateString()}</td>
                  <td style={{ padding: '12px 18px' }}>
                    <span style={{ padding: '2px 8px', borderRadius: '4px', fontSize: '10px', fontWeight: 700, backgroundColor: s.documentType === 'Factura' ? '#EFF6FF' : '#F9F5FF', color: s.documentType === 'Factura' ? '#1D4ED8' : '#6B21A8' }}>
                      {s.documentType}
                    </span>
                  </td>
                  <td style={{ padding: '12px 18px', fontWeight: 700 }}>{s.invoiceNumber}</td>
                  <td style={{ padding: '12px 18px' }}>{s.customerName}</td>
                  <td style={{ padding: '12px 18px', color: '#6B7280' }}>{s.customerDocument}</td>
                  <td style={{ padding: '12px 18px', textAlign: 'right', fontWeight: 700 }}>S/. {formatNoRound(s.totalAmount)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* ================= TAB 3: DETAILED PURCHASES LIST ================= */}
      {activeSubTab === 'purchases' && (
        <div style={{ backgroundColor: '#FFF', border: '1px solid #E5E7EB', borderRadius: '12px', overflow: 'hidden' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px', textAlign: 'left' }}>
            <thead>
              <tr style={{ backgroundColor: '#F9FAFB', borderBottom: '1px solid #E5E7EB' }}>
                <th style={{ padding: '12px 18px', fontWeight: 700 }}>Fecha</th>
                <th style={{ padding: '12px 18px', fontWeight: 700 }}>Tipo</th>
                <th style={{ padding: '12px 18px', fontWeight: 700 }}>Número</th>
                <th style={{ padding: '12px 18px', fontWeight: 700 }}>Proveedor</th>
                <th style={{ padding: '12px 18px', fontWeight: 700 }}>RUC Proveedor</th>
                <th style={{ padding: '12px 18px', fontWeight: 700, textAlign: 'right' }}>Monto Total</th>
                <th style={{ padding: '12px 18px', textAlign: 'right' }}>Acciones</th>
              </tr>
            </thead>
            <tbody>
              {filteredPurchases.map(p => (
                <tr key={p.id} style={{ borderBottom: '1px solid #F3F4F6' }}>
                  <td style={{ padding: '12px 18px' }}>{new Date(p.createdAt).toLocaleDateString()}</td>
                  <td style={{ padding: '12px 18px' }}>
                    <span style={{ padding: '2px 8px', borderRadius: '4px', fontSize: '10px', fontWeight: 700, backgroundColor: '#FEF2F2', color: '#991B1B' }}>
                      {p.documentType}
                    </span>
                  </td>
                  <td style={{ padding: '12px 18px', fontWeight: 700 }}>{p.invoiceNumber}</td>
                  <td style={{ padding: '12px 18px' }}>{p.customerName}</td>
                  <td style={{ padding: '12px 18px', color: '#6B7280' }}>{p.customerDocument}</td>
                  <td style={{ padding: '12px 18px', textAlign: 'right', fontWeight: 700 }}>S/. {formatNoRound(p.totalAmount)}</td>
                  <td style={{ padding: '12px 18px', textAlign: 'right' }}>
                    <button onClick={() => handleDeleteManual(p.id)} style={{ background: 'none', border: 'none', color: '#EF4444', cursor: 'pointer' }}>
                      <Trash2 size={14} />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* ================= MODAL: ADD COMPROBANTE ================= */}
      {showAddModal && (
        <div style={{
          position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
          backgroundColor: 'rgba(0,0,0,0.5)', zIndex: 6000,
          display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '20px'
        }}>
          <div style={{
            backgroundColor: '#FFF', width: '100%', maxWidth: '460px',
            borderRadius: '12px', padding: '24px', boxShadow: '0 20px 50px rgba(0,0,0,0.15)'
          }}>
            <h3 style={{ fontSize: '15px', fontWeight: 800, color: '#111', marginBottom: '16px', textTransform: 'uppercase' }}>
              Registrar Nuevo Comprobante
            </h3>

            {/* Drag & Drop PDF Import */}
            <div style={{
              border: '2px dashed #D1D5DB', borderRadius: '8px', padding: '16px',
              textAlign: 'center', marginBottom: '18px', backgroundColor: '#F9FAFB'
            }}>
              <Upload size={22} color="#C5A880" style={{ margin: '0 auto 8px' }} />
              <label style={{ fontSize: '12px', fontWeight: 700, color: '#374151', cursor: 'pointer', display: 'block' }}>
                📂 Importar Factura / Boleta en PDF
                <input type="file" accept="application/pdf" onChange={handlePdfUpload} style={{ display: 'none' }} />
              </label>
              <span style={{ fontSize: '10px', color: '#6B7280', display: 'block', marginTop: '4px' }}>
                El sistema escaneará y extraerá los datos automáticamente
              </span>
            </div>

            {importingPdf && <div style={{ fontSize: '12px', color: '#3B82F6', textAlign: 'center', marginBottom: '12px' }}>Analizando PDF...</div>}
            {pdfSuccessMessage && <div style={{ fontSize: '11px', color: '#10B981', backgroundColor: '#ECFDF5', padding: '8px', borderRadius: '4px', marginBottom: '12px' }}>{pdfSuccessMessage}</div>}

            <form onSubmit={handleSaveManualEntry} style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
                <div>
                  <label style={{ fontSize: '10px', fontWeight: 700, color: '#6B7280' }}>TIPO REGISTRO</label>
                  <select value={entryType} onChange={e => setEntryType(e.target.value)} style={{ width: '100%', padding: '8px', border: '1px solid #D1D5DB', borderRadius: '6px', backgroundColor: '#FFF' }}>
                    <option value="purchase">Compra (Gasto/RUC)</option>
                    <option value="sale">Venta Manual</option>
                  </select>
                </div>
                <div>
                  <label style={{ fontSize: '10px', fontWeight: 700, color: '#6B7280' }}>COMPROBANTE</label>
                  <select value={docType} onChange={e => setDocType(e.target.value)} style={{ width: '100%', padding: '8px', border: '1px solid #D1D5DB', borderRadius: '6px', backgroundColor: '#FFF' }}>
                    <option value="Factura">Factura</option>
                    <option value="Boleta">Boleta</option>
                  </select>
                </div>
              </div>

              <div>
                <label style={{ fontSize: '10px', fontWeight: 700, color: '#6B7280' }}>NÚMERO COMPROBANTE</label>
                <input type="text" value={docNumber} onChange={e => setDocNumber(e.target.value)} placeholder="Ej: F001-0004523" style={{ width: '100%', padding: '8px', border: '1px solid #D1D5DB', borderRadius: '6px' }} />
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1.4fr 1.6fr', gap: '10px' }}>
                <div>
                  <label style={{ fontSize: '10px', fontWeight: 700, color: '#6B7280' }}>{entryType === 'purchase' ? 'RUC PROVEEDOR' : 'DNI/RUC ADQUIRIENTE'}</label>
                  <input type="text" value={clientRuc} onChange={e => setClientRuc(e.target.value)} placeholder="Ej: 20601234567" style={{ width: '100%', padding: '8px', border: '1px solid #D1D5DB', borderRadius: '6px' }} />
                </div>
                <div>
                  <label style={{ fontSize: '10px', fontWeight: 700, color: '#6B7280' }}>{entryType === 'purchase' ? 'RAZÓN SOCIAL PROVEEDOR' : 'NOMBRE CLIENTE'}</label>
                  <input type="text" value={clientName} onChange={e => setClientName(e.target.value)} placeholder="Ej: Textil Peruano S.A.C." style={{ width: '100%', padding: '8px', border: '1px solid #D1D5DB', borderRadius: '6px' }} />
                </div>
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
                <div>
                  <label style={{ fontSize: '10px', fontWeight: 700, color: '#6B7280' }}>MONTO TOTAL (S/.)</label>
                  <input type="number" value={amountTotal} onChange={e => setAmountTotal(e.target.value)} placeholder="0.00" style={{ width: '100%', padding: '8px', border: '1px solid #D1D5DB', borderRadius: '6px', fontWeight: 700 }} />
                </div>
                <div>
                  <label style={{ fontSize: '10px', fontWeight: 700, color: '#6B7280' }}>FECHA EMISIÓN</label>
                  <input type="date" value={dateStr} onChange={e => setDateStr(e.target.value)} style={{ width: '100%', padding: '8px', border: '1px solid #D1D5DB', borderRadius: '6px' }} />
                </div>
              </div>

              <div style={{ display: 'flex', gap: '10px', marginTop: '12px' }}>
                <button type="submit" style={{ flex: 1, padding: '10px', fontSize: '13px', fontWeight: 700, backgroundColor: '#111', color: '#C5A880', border: 'none', borderRadius: '6px', cursor: 'pointer' }}>
                  Guardar Registro
                </button>
                <button type="button" onClick={() => { setShowAddModal(false); setPdfSuccessMessage(''); }} style={{ flex: 1, padding: '10px', fontSize: '13px', fontWeight: 700, backgroundColor: '#F3F4F6', color: '#4B5563', border: '1px solid #E5E7EB', borderRadius: '6px', cursor: 'pointer' }}>
                  Cancelar
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

    </div>
  );
}
